project:
  type: book

execute:
  keep-md: true

book:
  title: "New Interactive Visual Tools and Statistical Methodology for Selecting and Evaluating Non-linear Dimension Reduction Layouts of High-dimensional Data"
  author: "Piyadi Gamage Jayani Lakshika"
  repo-url: https://github.com/JayaniLakshika/Monash_PhD_thesis
  repo-subdir: Thesis
  repo-actions: [edit]
  repo-branch: master
  downloads: [pdf]
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "abstract.qmd"
    - "acknowledgements.qmd"
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "05-chap5.qmd"
    - "06-chap6.qmd"
    - "refs.qmd"
  appendices:
    - "A-appA.qmd"
    - "B-appB.qmd"
    - "C1-appC1.qmd"
    - "C2-appC2.qmd"
    - "C3-appC3.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2026
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Sc. (Hons) in Statistics, University of Sri Jayewardenepura (USJ), Sri Lanka'

format:
  monashthesis-html: default
  monashthesis-pdf:
    shorttitle: "interactive and dynamic graphics for studying non-linear dimension reduction models of high-dimensional data"
    link-citations: true
    include-in-header:
      - text: |
          \usepackage{pmboxdraw}
          \newcommand{\CRANpkg}[1]{\textsf{#1}}
          \usepackage{amsmath}
          \usepackage{array}
          \usepackage{float}
          \newcommand\pD{$p\text{-}D$}
          \newcommand\gD{$2\text{-}D$}
