project:
  type: book
  output-dir: _book

execute:
  keep-md: true

book:
  title: "New Interactive Visual Tools and Statistical Methodology for Selecting and Evaluating Non-linear Dimension Reduction Layouts of High-dimensional Data"
  author: "Piyadi Gamage Jayani Lakshika"
  repo-url: https://github.com/JayaniLakshika/Monash_PhD_thesis
  repo-subdir: Thesis
  repo-actions: [edit]
  repo-branch: master
  downloads: [pdf]
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "preliminaries/abstract.qmd"
    - "preliminaries/acknowledgements.qmd"
    - "chapters/01-chap1.qmd"
    - "chapters/02-chap2.qmd"
    - "chapters/03-chap3.qmd"
    - "chapters/04-chap4.qmd"
    - "chapters/05-chap5.qmd"
    - "chapters/06-chap6.qmd"
    - "chapters/07-chap7.qmd"
    - "refs.qmd"
  appendices:
    - "appendix/A-appA.qmd"
    - "appendix/B-appB.qmd"
    - "appendix/C-appC.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2026
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Sc. (Hons) in Statistics, University of Sri Jayewardenepura (USJ), Sri Lanka'

format:
  monashthesis-html: default
  monashthesis-pdf:
    shorttitle: "interactive and dynamic graphics for studying non-linear dimension reduction models of high-dimensional data"
    link-citations: true
    include-in-header:
      - text: |
          \usepackage{pmboxdraw}
          \newcommand{\CRANpkg}[1]{\textsf{#1}}
          \usepackage{amsmath}
          \usepackage{float}
          \usepackage{hyperref}
          \usepackage[utf8]{inputenc}
          \usepackage{bm}
          \def\tightlist{}
          \usepackage{setspace}
          \newcommand\pD{$p\text{-}D$}
          \newcommand\kD{$k\text{-}D$}
          \newcommand\dD{$d\text{-}D$}
          \newcommand\gD{$2\text{-}D$}
          \newcommand{\twoD}{$2\text{-}D$}
          \newcommand\tD{$3\text{-}D$}
          \newcommand\fD{$4\text{-}D$}
          \newcommand\sD{$7\text{-}D$}
          \usepackage{bm}
          \newcommand{\mathbfit}[1]{\bm{#1}}
