# Appendix to "Perception and Misperception of Clustering in Nonlinear Dimension Reduction: A User Study" {#sec-appendix-b}

```{r include=FALSE}
# Set up chunk for for knitr
knitr::opts_chunk$set(
  fig.width = 5,
  fig.height = 5,
  fig.align = "center",
  out.width = "100%",
  code.line.numbers = FALSE,
  fig.retina = 4,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  dev.args = list(pointsize = 11)
)
```

```{r}
library(ggplot2)
library(tibble)
library(purrr)
library(dplyr)
library(quollr)
library(readr)
library(tidyr)
library(patchwork)
library(kableExtra)
library(colorspace)
```

```{r}
#| label: import-scripts
source(here::here("scripts/vis-exp/additional_functions.R"))
```

```{r}
#| label: code-setup
set.seed(20240110)
```

```{r}
#| label: plot-theme
theme_set(theme_linedraw() +
   theme(
     #aspect.ratio = 1,
     plot.background = element_rect(fill = 'transparent', colour = NA),
     plot.title = element_text(size = 7, hjust = 0.5, vjust = -0.5),
     panel.background = element_rect(fill = 'transparent', 
                                     colour = NA),
     panel.grid.major = element_blank(), 
     panel.grid.minor = element_blank(), 
     axis.title.x = element_blank(), axis.title.y = element_blank(),
     axis.text.x = element_blank(), axis.ticks.x = element_blank(),
     axis.text.y = element_blank(), axis.ticks.y = element_blank(),
     legend.background = element_rect(fill = 'transparent', 
                                      colour = NA),
     legend.key = element_rect(fill = 'transparent', 
                               colour = NA),
     legend.position = "bottom", 
     legend.title = element_blank(), 
     legend.text = element_text(size=4),
     legend.key.height = unit(0.25, 'cm'),
     legend.key.width = unit(0.25, 'cm')
   )
)
```

## Videos links

Animations of the \pD{} tours that used for the study are available on YouTube at the links given in @tbl-links-html.

```{r}
links_df <- tibble::tibble(
  `data structure` = paste0("three_clust_", sprintf("%02d", 1:18)),
  small = c('<a href="https://youtu.be/kZyZxujDz58">youtu.be/kZyZxujDz58</a>', '<a href="https://youtu.be/CLMlOU4Fb2w">youtu.be/CLMlOU4Fb2w</a>', '<a href="https://youtu.be/K2oKM4mUBXM">youtu.be/K2oKM4mUBXM</a>', '<a href="https://youtu.be/7yvvpPgiWNw">youtu.be/7yvvpPgiWNw</a>', '<a href="https://youtu.be/pbI7UXFgc0k">youtu.be/pbI7UXFgc0k</a>', '<a href="https://youtu.be/Mxylk4M67iA">youtu.be/Mxylk4M67iA</a>', '<a href="https://youtu.be/2a89BQGK_iU">youtu.be/2a89BQGK_iU</a>', '<a href="https://youtu.be/eID-dwpgU44">youtu.be/eID-dwpgU44</a>','<a href="https://youtu.be/6uGCDUSL60Q">youtu.be/6uGCDUSL60Q</a>','<a href="https://youtu.be/CX5O4eNZW5o">youtu.be/CX5O4eNZW5o</a>','<a href="https://youtu.be/1f8S7HiZ8dc">youtu.be/1f8S7HiZ8dc</a>','<a href="https://youtu.be/AZv45NGkuC4">youtu.be/AZv45NGkuC4</a>','<a href="https://youtu.be/U-bbZjzvaiE">youtu.be/U-bbZjzvaiE</a>','<a href="https://youtu.be/ynu2oUxv08I">youtu.be/ynu2oUxv08I</a>','<a href="https://youtu.be/xsdWsBek0eQ">youtu.be/xsdWsBek0eQ</a>','<a href="https://youtu.be/VyYyYOqhOVs">youtu.be/VyYyYOqhOVs</a>','<a href="https://youtu.be/yojgjcf2NQk">youtu.be/yojgjcf2NQk</a>','<a href="https://youtu.be/r-Z1Yyf2c4s">youtu.be/r-Z1Yyf2c4s</a>'),
  medium = c('<a href="https://youtu.be/Jz3k4uIAiRo">youtu.be/Jz3k4uIAiRo</a>', '<a href="https://youtu.be/TFj0satlBBE">youtu.be/TFj0satlBBE</a>', '<a href="https://youtu.be/b-43HKN30ws">youtu.be/b-43HKN30ws</a>', '<a href="https://youtu.be/1PhZO7cUEaI">youtu.be/1PhZO7cUEaI</a>', '<a href="https://youtu.be/G-TvOIBj-14">youtu.be/G-TvOIBj-14</a>', '<a href="https://youtu.be/ABrxozu8F-A">youtu.be/ABrxozu8F-A</a>', '<a href="https://youtu.be/Wt4NwZSACmo">youtu.be/Wt4NwZSACmo</a>', '<a href="https://youtu.be/ILwnlZUMj_U">youtu.be/ILwnlZUMj_U</a>','<a href="https://youtu.be/RvlSY3drV5I">youtu.be/RvlSY3drV5I</a>','<a href="https://youtu.be/fHxflXa9i-s">youtu.be/fHxflXa9i-s</a>','<a href="https://youtu.be/Fki5vIuPupE">youtu.be/Fki5vIuPupE</a>','<a href="https://youtu.be/qQ4LqHYH_c4">youtu.be/qQ4LqHYH_c4</a>','<a href="https://youtu.be/0MznMYr5gfo">youtu.be/0MznMYr5gfo</a>','<a href="https://youtu.be/gHDLMn5AG-8">youtu.be/gHDLMn5AG-8</a>','<a href="https://youtu.be/SDY64MrcWQg">youtu.be/SDY64MrcWQg</a>','<a href="https://youtu.be/zi-TvgVR8a4">youtu.be/zi-TvgVR8a4</a>','<a href="https://youtu.be/UJPMJ5irRbQ">youtu.be/UJPMJ5irRbQ</a>','<a href="https://youtu.be/2Rf2L8iey2w">youtu.be/2Rf2L8iey2w</a>'),
  large = c('<a href="https://youtu.be/E9msE_XX0KA">youtu.be/E9msE_XX0KA</a>', '<a href="https://youtu.be/_f2WvtD2xog">youtu.be/f2WvtD2xog</a>', '<a href="https://youtu.be/7NwNcD4qlLc">youtu.be/7NwNcD4qlLc</a>', '<a href="https://youtu.be/XO61YVXAdr8">youtu.be/XO61YVXAdr8</a>', '<a href="https://youtu.be/ardE0G7zevk">youtu.be/ardE0G7zevk</a>', '<a href="https://youtu.be/soFQR9UwNsg">youtu.be/soFQR9UwNsg</a>', '<a href="https://youtu.be/hVwIjSxACoo">youtu.be/hVwIjSxACoo</a>', '<a href="https://youtu.be/oSBaMH9HJZ4">youtu.be/oSBaMH9HJZ4</a>', '<a href="https://youtu.be/mh_rG2qy2Pc">youtu.be/mh_rG2qy2Pc</a>', '<a href="https://youtu.be/R6vD1xJH21w">youtu.be/R6vD1xJH21w</a>', '<a href="https://youtu.be/ciVOD8_sWR0">youtu.be/ciVOD8_sWR0</a>', '<a href="https://youtu.be/Y2sfVoemVZo">youtu.be/Y2sfVoemVZo</a>', '<a href="https://youtu.be/E7ge3kw5Q0Q">youtu.be/E7ge3kw5Q0Q</a>','<a href="https://youtu.be/HyCJEiwCVv0">youtu.be/HyCJEiwCVv0</a>','<a href="https://youtu.be/CFIyW7ftF9M">youtu.be/CFIyW7ftF9M</a>','<a href="https://youtu.be/hdQmD499yo8">youtu.be/hdQmD499yo8</a>','<a href="https://youtu.be/zdQYQvqTyGA">youtu.be/zdQYQvqTyGA</a>','<a href="https://youtu.be/e_-IQycglVE">youtu.be/e_-IQycglVE</a>')
)
```

```{r}
#| label: tbl-links-html
#| tbl-pos: H
#| tbl-cap: "Videos"

links_df |>
  kableExtra::kable(
    format = "html",
    label = "tbllinks",
    escape = FALSE, 
    booktabs = TRUE
  )

```
