# Glossary

```{r}
source(here::here("scripts/software.R"))
```

```{r}
#| label: tbl-glossary
#| tbl-pos: H
#| tbl-cap: "Glossary."
# Keywords used in the thesis

glossary_df <- read_csv(here::here("misc/glossary.csv")) |>
  arrange(Term)

glossary_df[] <- lapply(glossary_df, function(x) {
  if (is.character(x)) {
    iconv(x, from = "", to = "UTF-8", sub = "")
  } else {
    x
  }
})

if (knitr::is_latex_output()) {
  
  glossary_df$Term[glossary_df$Term == "`autoAlt`"] <- "\\texttt{autoAlt}"
  glossary_df$Term[glossary_df$Term == "`cardinalR`"] <- "\\texttt{cardinalR}"
  glossary_df$Term[glossary_df$Term == "`detourr`"] <- "\\texttt{detourr}"
  glossary_df$Term[glossary_df$Term == "`knitr`"] <- "\\texttt{knitr}"
  glossary_df$Term[glossary_df$Term == "`langevitour`"] <- "\\texttt{langevitour}"
  glossary_df$Term[glossary_df$Term == "`menuraR`"] <- "\\texttt{menuraR}"
  glossary_df$Term[glossary_df$Term == "`quollr`"] <- "\\texttt{quollr}"
  glossary_df$Term[glossary_df$Term == "`shiny`"] <- "\\texttt{shiny}"
  
  kable(glossary_df, 
      format = "latex", 
      booktabs = TRUE, escape = FALSE, longtable = TRUE, linesep = "") |>
    kable_styling(position = "center", 
                full_width = FALSE, 
                font_size = 12,
                latex_options = c("repeat_header")) |>
    row_spec(0, bold = TRUE) |>
    column_spec(1:2, width = c("4cm", "11cm"))
} else {

  kable(glossary_df, escape = FALSE) 
}
```
